const { REACT_APP_API_URL, REACT_APP_NAME, REACT_APP_CRYPTO_STORAGE_KEY } =
    process.env;

const API_URL = REACT_APP_API_URL;
const ADMIN_NAME = REACT_APP_NAME;
const CRYPTO_STORAGE_KEY = REACT_APP_CRYPTO_STORAGE_KEY;

export { API_URL, ADMIN_NAME, CRYPTO_STORAGE_KEY };
